[theme]
primaryColor="#0033A0"           # Dark blue (buttons, highlights)
backgroundColor="#FFFFFF"        # White page background
secondaryBackgroundColor="#da1a32"  # Prep Red
textColor="#0033A0"              # Dark blue text
font="sans serif"
